# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WaterlevelPrediction
                                 A QGIS plugin
 This plugin is water level prediction.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-23
        copyright            : (C) 2022 by Lee / Corp.
        email                : woonss@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WaterlevelPrediction class from file WaterlevelPrediction.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .waterlevel_prediction import WaterlevelPrediction
    return WaterlevelPrediction(iface)
